// Generated by gencpp from file server/Position.msg
// DO NOT EDIT!


#ifndef SERVER_MESSAGE_POSITION_H
#define SERVER_MESSAGE_POSITION_H

#include <ros/service_traits.h>


#include <server/PositionRequest.h>
#include <server/PositionResponse.h>


namespace server
{

struct Position
{

typedef PositionRequest Request;
typedef PositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Position
} // namespace server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::server::Position > {
  static const char* value()
  {
    return "36c8dcf1c5586f27520f2080e30f4ae0";
  }

  static const char* value(const ::server::Position&) { return value(); }
};

template<>
struct DataType< ::server::Position > {
  static const char* value()
  {
    return "server/Position";
  }

  static const char* value(const ::server::Position&) { return value(); }
};


// service_traits::MD5Sum< ::server::PositionRequest> should match
// service_traits::MD5Sum< ::server::Position >
template<>
struct MD5Sum< ::server::PositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::server::Position >::value();
  }
  static const char* value(const ::server::PositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::server::PositionRequest> should match
// service_traits::DataType< ::server::Position >
template<>
struct DataType< ::server::PositionRequest>
{
  static const char* value()
  {
    return DataType< ::server::Position >::value();
  }
  static const char* value(const ::server::PositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::server::PositionResponse> should match
// service_traits::MD5Sum< ::server::Position >
template<>
struct MD5Sum< ::server::PositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::server::Position >::value();
  }
  static const char* value(const ::server::PositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::server::PositionResponse> should match
// service_traits::DataType< ::server::Position >
template<>
struct DataType< ::server::PositionResponse>
{
  static const char* value()
  {
    return DataType< ::server::Position >::value();
  }
  static const char* value(const ::server::PositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVER_MESSAGE_POSITION_H
