// Generated by gencpp from file server/PositionRequest.msg
// DO NOT EDIT!


#ifndef SERVER_MESSAGE_POSITIONREQUEST_H
#define SERVER_MESSAGE_POSITIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace server
{
template <class ContainerAllocator>
struct PositionRequest_
{
  typedef PositionRequest_<ContainerAllocator> Type;

  PositionRequest_()
    : X(0)  {
    }
  PositionRequest_(const ContainerAllocator& _alloc)
    : X(0)  {
  (void)_alloc;
    }



   typedef int64_t _X_type;
  _X_type X;





  typedef boost::shared_ptr< ::server::PositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::server::PositionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PositionRequest_

typedef ::server::PositionRequest_<std::allocator<void> > PositionRequest;

typedef boost::shared_ptr< ::server::PositionRequest > PositionRequestPtr;
typedef boost::shared_ptr< ::server::PositionRequest const> PositionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::server::PositionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::server::PositionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::server::PositionRequest_<ContainerAllocator1> & lhs, const ::server::PositionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.X == rhs.X;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::server::PositionRequest_<ContainerAllocator1> & lhs, const ::server::PositionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::server::PositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::server::PositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::server::PositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::server::PositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server::PositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server::PositionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::server::PositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1e404dd3cb6d4bfb308931d7bf3cfb43";
  }

  static const char* value(const ::server::PositionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1e404dd3cb6d4bfbULL;
  static const uint64_t static_value2 = 0x308931d7bf3cfb43ULL;
};

template<class ContainerAllocator>
struct DataType< ::server::PositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "server/PositionRequest";
  }

  static const char* value(const ::server::PositionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::server::PositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 X\n"
;
  }

  static const char* value(const ::server::PositionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::server::PositionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.X);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PositionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::server::PositionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::server::PositionRequest_<ContainerAllocator>& v)
  {
    s << indent << "X: ";
    Printer<int64_t>::stream(s, indent + "  ", v.X);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVER_MESSAGE_POSITIONREQUEST_H
