// Generated by gencpp from file client/Position.msg
// DO NOT EDIT!


#ifndef CLIENT_MESSAGE_POSITION_H
#define CLIENT_MESSAGE_POSITION_H

#include <ros/service_traits.h>


#include <client/PositionRequest.h>
#include <client/PositionResponse.h>


namespace client
{

struct Position
{

typedef PositionRequest Request;
typedef PositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Position
} // namespace client


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::client::Position > {
  static const char* value()
  {
    return "36c8dcf1c5586f27520f2080e30f4ae0";
  }

  static const char* value(const ::client::Position&) { return value(); }
};

template<>
struct DataType< ::client::Position > {
  static const char* value()
  {
    return "client/Position";
  }

  static const char* value(const ::client::Position&) { return value(); }
};


// service_traits::MD5Sum< ::client::PositionRequest> should match
// service_traits::MD5Sum< ::client::Position >
template<>
struct MD5Sum< ::client::PositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::client::Position >::value();
  }
  static const char* value(const ::client::PositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::client::PositionRequest> should match
// service_traits::DataType< ::client::Position >
template<>
struct DataType< ::client::PositionRequest>
{
  static const char* value()
  {
    return DataType< ::client::Position >::value();
  }
  static const char* value(const ::client::PositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::client::PositionResponse> should match
// service_traits::MD5Sum< ::client::Position >
template<>
struct MD5Sum< ::client::PositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::client::Position >::value();
  }
  static const char* value(const ::client::PositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::client::PositionResponse> should match
// service_traits::DataType< ::client::Position >
template<>
struct DataType< ::client::PositionResponse>
{
  static const char* value()
  {
    return DataType< ::client::Position >::value();
  }
  static const char* value(const ::client::PositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLIENT_MESSAGE_POSITION_H
